Document: m4api
Title: Debian m4api Manual
Author: <insert document author here>
Abstract: This manual describes what m4api is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/m4api/m4api.sgml.gz

Format: postscript
Files: /usr/share/doc/m4api/m4api.ps.gz

Format: text
Files: /usr/share/doc/m4api/m4api.text.gz

Format: HTML
Index: /usr/share/doc/m4api/html/index.html
Files: /usr/share/doc/m4api/html/*.html
